name: Generate extension bundles

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'

jobs:
  generate-extension-bundles:
    name: Generate extension bundles
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - run: yarn install --immutable | grep -v 'YN0013' # as in the polkadot workflows

      - run: yarn download-chains-metadata
      # we are setting the version on the source code (before the build phase), because the source code
      # is zipped and sent to mozilla for verification, so that the actual bundle needs to be buildable from it
      - run: yarn set-signer-version --version=${{ github.ref_name }}
      - run: yarn polkadot-dev-build-ts
      - run: yarn build:zip

      - uses: actions/upload-artifact@v3
        with:
          name: signer-extension-bundles-v${{ github.ref_name }}
          retention-days: 30
          if-no-files-found: error
          path: |
            extension-chrome.zip
            extension-firefox.zip
            source-code.zip
